### ISSUE TITLE
Steam games do not display properly

### ISSUE THREAD

**Issue by stickyfusion** [n3uromanc3r/steam-library-gt#2]
I just installed this plugin and the steam games display on my page is a very long straight light down the page. Is there any way to make them display in more of a grid like your example page?

**Comment by n3uromanc3r** [comment]
Hi stickyfusion!  I'd be more than happy to help you!  First things first!... Could you provide a screenshot?  Is there a live version of this site I can examine?  

It sound like a CSS issue.  Are you using a custom theme?

**Comment by stickyfusion** [comment]
I am using a custom theme, I all almost home and I can provide you with screenshots, etc.

**Comment by n3uromanc3r** [comment]
No sweat.  I'll be going to bed shortly, but I'll pick up this issue tomorrow and see if we can get this fixed for you.

Take care! o/

**Comment by n3uromanc3r** [comment]
I just tested the plugin in the latest version of Wordpress and it still works fine, so it must be a conflict with your theme.  We should be able to fix it up easily enough! ;)

**Comment by stickyfusion** [comment]
Well one thing that does happen is when I have the plugin active i am
unable to drag my widgets to widget areas and I disabled plugins until I
got to yours and it resolved it. Any ideas there?

**Comment by n3uromanc3r** [comment]
Is this website of yours available to access? I'd like to inspect the css and markup.

**Comment by stickyfusion** [comment]
Yeah I am kind of giving up. There is another plugin that I like that shows
if the person is currently online, etc and what games they have. That's
whats on the page now. Like I said I can't enable yours because it breaks a
lot of my other stuff in the backend. http://dpgx.dynamic-dns.net

**Comment by n3uromanc3r** [comment]
I've only really tested this on a vanilla wordpress installation... and it works fine.

I have a feeling that it may be a conflict between some plugins.  I can't really inspect anything on your site, because the GT plugin is not enabled, plus I don't have backend access.

If you could list all your plugins and your theme.  I'll install them on a test environment and debug from there.

I'll certainly do my best to help you fix it, if you can be bothered to help me help you! ;)

This is what is should be like (roughly, this is the non-wordpress version... the wordpress version has an improved ajax loader and tweaked css) http://steam.virusav.com/

**Comment by stickyfusion** [comment]
I can give you Backend access I don't care lol if that's best.

**Comment by n3uromanc3r** [comment]
If you're willing to do that, then I'll go in and try to locate the cause of the problem.  Email me on keito@virusav.com and we'll go from there.

**Comment by stickyfusion** [comment]
I am new to Wordpress so I am not technical with code. I know what I want things to look like and I ret to make it happen, unsuccessfully more times than not but thanks for the help.

**Comment by n3uromanc3r** [comment]
Not a problem at all.  I work with code all the time, though this wordpress plugin was just for fun.

Thanks for pointing out the issue though.  There is a breakage with the widget page (after searching Google for this, it would appear that lots of plugins suffer the same breakage too!).  I've fixed this and pushed the updated code to github and the wordpress plugin site too.

This is one thing fixed, but I still haven't seen the visual bug you experience with the plugin.  I'll email you to discuss this further.

**Comment by stickyfusion** [comment]
OK, well i can't figure out how to get your plugin to work, I must be doing
something wrong. The page i want it on is called "Steam Friends". I have
another plugin on it that I like the output of a lot but i can't figure out
how to get that one to display in rows side by side rather than down the
page. I keep adding them and they keep scrolling. I am new to this and I am
sure it has everything to do with the style sheet and the divs but I wanted
to try your plugin as well.

**Comment by n3uromanc3r** [comment]
Sorry, been busy these last few days.  I'll have to do some investigation when I get a chance in the next few days.  Leave it with me, I'll get to the bottom of it! =)

**Comment by n3uromanc3r** [comment]
All sorted, it was a style conflict with bootstrap.  Not a bug! ;)

**Comment by stickyfusion** [comment]
Really? can you explain a tad for the noobie like me?

**Comment by stickyfusion** [comment]
Also is it possible to have the Steam ID handle appear under the header?
And even have the 2 entries appear side by side?

**Comment by n3uromanc3r** [comment]
Your site is using bootstrap, which sets out a bunch of styles that apply to your page.  Some of these styles were messing with the (relatively minimal) styles that the Steam Library GT plugin uses.  So, basically, the container div for the plugin was set to 184px wide, when it should be 100%.  Hence, you had a long thin column of images, one image wide.

I simply applied some additional styling to the steam.css (in your wordpress install only), to set "width: 100% !important"... this ensures that the bootstrap style gets overridden.

As for the additional style tweaks you require, I sent you an email about this (basically, a bit of a cop-out on my part - but I'm super-busy).  In short, you should read up on CSS, in order to help you create and style websites!.

To point you in the right direction... The page Steam LIbrary GT is used on simply has the widget embed code within it [steam-library-gt].  You could try putting this inside a div and set the width of that div to be something like 65%, then have another div alongside it (you can float or use display inline-block to achieve this) with your other plugin in.  At the top of the page, add a header with your Steam ID handle.

**Comment by n3uromanc3r** [comment]
So, I just had a quick dabble for you, because I'm a nice guy!  Anyhow, I noticed the modal was still problematic (z-index), so rectified that.  I also tried to sit the two plugins alongside one another.  The method I detailed above won't work, as by adding the widget to the page, it overrides all other possible content.  It may be possible to use the widget as a sidebar to get around this, but it would require some research to find out how to do so.  If it isn't possible, you could edit the source of the plugin to make it so (there is ALWAYS a way!), something like this perhaps?... http://wordpress.org/support/topic/add-html-wrapper-around-widget-content

Good luck!

**Comment by stickyfusion** [comment]
Thanks so much for all of your help.
